In [87]:
# auto-reload modules
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [88]:
from Value import *

In [89]:
a = Value(2)
b = Value(3)

c = a + b
c.backward()
c.grad, a.grad, b.grad

(array(1., dtype=float32), array(1., dtype=float32), array(1., dtype=float32))

In [90]:
d = a * b
d.backward()
d.grad, a.grad, b.grad

(array(1., dtype=float32), array(4., dtype=float32), array(3., dtype=float32))

In [91]:
e = Value(-8)
f = e.relu()
f.backward()
f.grad, e.grad

(array(1., dtype=float32), array(0., dtype=float32))

In [92]:
g = Value([[-1, 5]])
gl0 = g.cross_entropy_loss([0])
gl0.zero_grad()
gl0.backward()
gl0.value, gl0.grad, g.grad

(array(6.0024757, dtype=float32),
 1.0,
 array([[-0.99752736,  0.9975274 ]], dtype=float32))

In [93]:
gl1 = g.cross_entropy_loss([1])
gl1.zero_grad()
gl1.backward()
print(gl1.value)
print(g.grad)
g.value -= g.grad
gl1 = g.cross_entropy_loss([1])
print(gl1.value)        # gl1 value should be decreased

0.0024756414
[[ 0.00247262 -0.00247258]]
0.0024635117


In [94]:
h = a + b       # a = 2, b = 3
i = h * b + a * b
i.zero_grad()
i.backward()
print(h.grad)   # expected: b * di = 3 * 1 = 3
print(b.grad)   # expected: (h + a) * di + dh = (5 + 2) * 1 + 3 = 10
print(a.grad)   # expected: b * di + dh = 3 + 3 = 6

3.0
10.0
6.0


In [95]:
A = Value(np.array([
    [1, 2],
    [3, 4]
]))
B = Value(np.array([
    [5, 6],
    [7, 8]
]))
C = A.mm(B)
C.zero_grad()
C.backward(np.identity(2))
C.grad, B.grad, A.grad

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 3.],
        [2., 4.]]),
 array([[5., 7.],
        [6., 8.]]))

In [96]:
p = Value(np.array([2, 3]))
q = A.mm(p)
q.zero_grad()
q.backward(np.ones_like(q.value))
q.value, q.grad, A.grad, p.grad

(array([ 8., 18.], dtype=float32),
 array([1., 1.], dtype=float32),
 array([[2., 3.],
        [2., 3.]], dtype=float32),
 array([4., 6.], dtype=float32))

In [97]:
r = Value(np.array([[1, 2]]))
s = r.mm(A)
s.zero_grad()
s.backward(np.ones_like(s.value))
s.value, s.grad, A.grad, r.grad

(array([[ 7., 10.]], dtype=float32),
 array([[1., 1.]], dtype=float32),
 array([[1., 1.],
        [2., 2.]], dtype=float32),
 array([[3., 7.]], dtype=float32))

In [101]:
D = Value(np.array([
    [1, 2],
    [3, 4],
    [5, 6]
]))
E = D.T
E.zero_grad()
E.backward(E)
E.grad, D.grad

[[1. 3. 5.]
 [2. 4. 6.]]


TypeError: unsupported operand type(s) for +=: 'float' and 'Value'